// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNkZqje0npcuPYxOwLSfS6HjLYa_Sb-48',
    appId: '1:1021672382316:web:afbadd394cb475db05dd49',
    messagingSenderId: '1021672382316',
    projectId: 'malab-77af4',
    authDomain: 'malab-77af4.firebaseapp.com',
    storageBucket: 'malab-77af4.firebasestorage.app',
    measurementId: 'G-586RWR1YRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4yK4_kUXPK-oY9D7iettWM-OIQdo16Ws',
    appId: '1:1021672382316:android:566e12dcd1cec2e805dd49',
    messagingSenderId: '1021672382316',
    projectId: 'malab-77af4',
    storageBucket: 'malab-77af4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd_WNmbE82KZiziNEi2qLrItuEepiortU',
    appId: '1:1021672382316:ios:38cc9a373de91f8f05dd49',
    messagingSenderId: '1021672382316',
    projectId: 'malab-77af4',
    storageBucket: 'malab-77af4.firebasestorage.app',
    iosBundleId: 'com.example.malab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd_WNmbE82KZiziNEi2qLrItuEepiortU',
    appId: '1:1021672382316:ios:38cc9a373de91f8f05dd49',
    messagingSenderId: '1021672382316',
    projectId: 'malab-77af4',
    storageBucket: 'malab-77af4.firebasestorage.app',
    iosBundleId: 'com.example.malab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNkZqje0npcuPYxOwLSfS6HjLYa_Sb-48',
    appId: '1:1021672382316:web:4aa76b52ef689e1e05dd49',
    messagingSenderId: '1021672382316',
    projectId: 'malab-77af4',
    authDomain: 'malab-77af4.firebaseapp.com',
    storageBucket: 'malab-77af4.firebasestorage.app',
    measurementId: 'G-XG7G4RG7DP',
  );
}
